import { WasteInfo, Scenario, QuizQuestion, Language, UIStrings } from './types';

export const UI_STRINGS: Record<Language, UIStrings> = {
  pt: {
    dashboard: 'Dashboard',
    groups: 'Grupos RSS',
    scenarios: 'Cenários',
    quiz: 'Quiz',
    history: 'Histórico',
    back: 'Voltar',
    search: 'Buscar resíduos, siglas ou tipos...',
    risks: 'Riscos Associados',
    mistakes: 'Erros Comuns de Descarte',
    technicalSummary: 'Resumo Técnico',
    practicalTipTitle: 'Dica Prática para o Dia a Dia',
    share: 'Compartilhar recurso!',
    examplesTitle: 'Exemplos de Resíduos',
    instructions: 'Instruções de Descarte',
    container: 'Recipiente Recomendado',
    clearHistory: 'Limpar Histórico',
    noHistory: 'Nenhum histórico encontrado',
    noHistorySub: 'Suas atividades aparecerão aqui conforme você navega pelos protocolos e realiza os desafios.',
    results: 'Resultados',
    score: 'Sua pontuação',
    restart: 'Reiniciar Quiz'
  },
  en: {
    dashboard: 'Dashboard',
    groups: 'Waste Groups',
    scenarios: 'Scenarios',
    quiz: 'Quiz',
    history: 'History',
    back: 'Back',
    search: 'Search for waste, acronyms or types...',
    risks: 'Associated Risks',
    mistakes: 'Common Disposal Mistakes',
    technicalSummary: 'Technical Summary',
    practicalTipTitle: 'Practical Tip for Daily Work',
    share: 'Share resource!',
    examplesTitle: 'Waste Examples',
    instructions: 'Disposal Instructions',
    container: 'Recommended Container',
    clearHistory: 'Clear History',
    noHistory: 'No history found',
    noHistorySub: 'Your activities will appear here as you navigate through protocols and complete challenges.',
    results: 'Results',
    score: 'Your score',
    restart: 'Restart Quiz'
  },
  es: {
    dashboard: 'Inicio',
    groups: 'Grupos RSS',
    scenarios: 'Escenarios',
    quiz: 'Quiz',
    history: 'Historial',
    back: 'Volver',
    search: 'Buscar residuos, siglas o tipos...',
    risks: 'Riesgos asociados',
    mistakes: 'Errores comunes de descarte',
    technicalSummary: 'Resumen técnico',
    practicalTipTitle: 'Consejo práctico para el día a día',
    share: 'Compartir recurso',
    examplesTitle: 'Ejemplos de residuos',
    instructions: 'Instrucciones de descarte',
    container: 'Recipiente recomendado',
    clearHistory: 'Limpiar historial',
    noHistory: 'No se encontró historial',
    noHistorySub: 'Sus actividades aparecerán aquí a medida que navegue por los protocolos y complete los desafíos.',
    results: 'Resultados',
    score: 'Su resultado',
    restart: 'Reiniciar quiz'
  }
};

export const WASTE_DATA: Record<Language, Record<string, WasteInfo>> = {
  pt: {
    A: {
      id: 'A',
      title: 'Grupo A: Perigo Biológico',
      subtitle: 'Resíduos Infectantes',
      description: 'Resíduos com a possível presença de agentes biológicos que, por suas características de maior virulência ou concentração, podem apresentar risco de infecção.',
      examples: [
        { label: 'Luvas com Sangue', description: 'Luvas manchadas de sangue usadas durante procedimentos.', icon: 'Droplets' },
        { label: 'Gazes e Curativos', description: 'Gazes e curativos de feridas abertas.', icon: 'Bandage' },
        { label: 'Bolsas Transfusoriais', description: 'Bolsas de transfusão de sangue vazias ou vencidas.', icon: 'HeartPulse' },
        { label: 'Meios de Cultura', description: 'Meios de cultura laboratorial e placas inoculadas.', icon: 'Microscope' },
      ],
      disposal: {
        instructions: 'Segregar conforme o subgrupo: saco vermelho quando houver tratamento obrigatório; saco branco leitoso para resíduos que não exigem tratamento ou após tratamento, conforme PGRSS.',
        container: 'Saco Branco/Vermelho',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      },
      risks: [
        'Exposição a patógenos como HIV e Hepatites (B e C).',
        'Contaminação cruzada em ambientes estéreis.',
      ],
      mistakes: [
        'Descartar papel toalha limpo no saco branco.',
        'Misturar perfurocortantes (Grupo E) no saco de infectantes.',
      ],
      summary: [
        { attribute: 'Identificação', specification: 'Símbolo de risco biológico em rótulo de fundo branco, desenho e contornos pretos, acrescido da expressão RESÍDUO INFECTANTE.', term: 'Anexo II - Grupo A' },
        { attribute: 'Saco e coletor', specification: 'RSS sólidos devem usar saco resistente a ruptura, vazamento e impermeável; o coletor deve ser lavável, resistente à punctura, ruptura, vazamento e tombamento, com tampa sem contato manual quando aplicável.', term: 'Arts. 13 e 17' },
        { attribute: 'Sem tratamento obrigatório', specification: 'RSS do Grupo A que não exigem tratamento obrigatório, e RSS após tratamento, são acondicionados em saco branco leitoso e seguem para disposição final ambientalmente adequada.', term: 'Art. 15' },
        { attribute: 'Tratamento obrigatório', specification: 'Quando houver obrigação de tratamento, usar saco vermelho; o saco branco pode substituir em regras locais de tratamento indiscriminado, exceto para subgrupo A5.', term: 'Art. 16' },
        { attribute: 'Limite de uso', specification: 'Substituir o saco ao atingir 2/3 da capacidade ou a cada 48 horas; resíduos de fácil putrefação devem ser substituídos em até 24 horas.', term: 'Art. 14' },
        { attribute: 'Subgrupo A5', specification: 'RSS do subgrupo A5 devem ser segregados em saco vermelho duplo, contidos em recipiente exclusivo identificado e encaminhados para incineração.', term: 'Art. 55' },
      ],
      practicalTip: 'Na dúvida, verifique se há sangue ou líquidos corpóreos na forma livre, suspeita de contaminação biológica ou enquadramento nos subgrupos A1 a A5 antes de descartar como Grupo A.',
    },
    B: {
      id: 'B',
      title: 'Grupo B: Resíduos Químicos',
      subtitle: 'Resíduos Químicos',
      description: 'Substâncias químicas que apresentam risco à saúde pública ou ao meio ambiente devido às suas características de inflamabilidade, corrosividade, reatividade ou toxicidade.',
      examples: [
        { label: 'Solventes Orgânicos', description: 'Inflamável: Frasco de vidro âmbar ou PEAD.', icon: 'FlaskConical' },
        { label: 'Ácido Sulfúrico', description: 'Corrosivo: Recipiente resistente a ácidos forte.', icon: 'TestTubeDiagonal' },
        { label: 'Medicamentos Vencidos', description: 'Tóxico: embalagem original ou recipiente compatível identificado.', icon: 'Pill' },
        { label: 'Metais Pesados', description: 'Persistente: Selagem hermética obrigatória.', icon: 'Skull' },
      ],
      disposal: {
        instructions: 'Utilizar recipiente compatível com o produto químico, resistente, estanque quando líquido, identificado com símbolo e frase de risco. Resíduos incompatíveis devem ficar separados.',
        container: 'Recipiente Compatível Identificado',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      },
      risks: [
        'Queimaduras Químicas: Lesões graves por contato direto com ácidos ou bases.',
        'Contaminação Ambiental: Danos irreversíveis a lençóis freáticos e fauna local.',
      ],
      mistakes: [
        'Descartar líquidos em pias comuns.',
        'Misturar substâncias incompatíveis.',
        'Omitir identificação no recipiente.',
      ],
      summary: [
        { attribute: 'Identificação', specification: 'Símbolo e frase de risco associados à periculosidade do resíduo químico; símbolos e frases do GHS podem ser usados conforme o risco.', term: 'Anexo II - Grupo B' },
        { attribute: 'Acondicionamento líquido', specification: 'Recipiente de material compatível com o líquido, resistente, rígido, estanque, com tampa que garanta contenção e identificação.', term: 'Art. 18' },
        { attribute: 'Acondicionamento sólido', specification: 'Recipiente rígido, resistente, compatível com as características do produto químico acondicionado e identificado.', term: 'Art. 19' },
        { attribute: 'Periculosidade', specification: 'O gerenciamento deve considerar inflamabilidade, corrosividade, reatividade e toxicidade, consultando FISPQ quando aplicável.', term: 'Art. 56' },
        { attribute: 'Incompatibilidade', specification: 'Produtos químicos incompatíveis devem ser segregados, acondicionados e identificados separadamente conforme risco e compatibilidade.', term: 'Art. 60 e Anexos III/IV' },
        { attribute: 'Tratamento e destino', specification: 'RSS químicos perigosos líquidos devem ser tratados antes da disposição final; é vedado encaminhar líquidos para aterro. Rejeitos sólidos perigosos seguem para aterro Classe I.', term: 'Arts. 57 e 58' },
      ],
      practicalTip: 'Todo resíduo químico deve estar devidamente rotulado com o nome da substância, data e responsável.',
    },
    C: {
      id: 'C',
      title: 'Grupo C: Resíduos Radioativos',
      subtitle: 'Resíduos Radioativos',
      description: 'Materiais que contêm radionuclídeos em quantidades superiores aos limites de isenção estabelecidos pela CNEN.',
      examples: [
        { label: 'Medicina Nuclear', description: 'Serviços de Medicina Nuclear e Radioterapia.', icon: 'Radiation' },
        { label: 'Pesquisa', description: 'Laboratórios de pesquisa com Radioisótopos.', icon: 'Microscope' },
        { label: 'Fluidos Corporais', description: 'Fluidos corporais de pacientes em tratamento.', icon: 'Droplets' },
        { label: 'Contaminados', description: 'Agulhas, seringas e luvas contaminadas.', icon: 'Biohazard' },
      ],
      disposal: {
        instructions: 'Seguir o Plano de Proteção Radiológica e normas da CNEN; armazenar para decaimento em condições adequadas, com blindagem quando indicada pelo supervisor de proteção radiológica.',
        container: 'Recipiente definido no PPR/CNEN',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      },
      risks: [
        'Radiação Ionizante: Danos celulares e mutações genéticas.',
        'Queimaduras Radiológicas: Lesões severas por exposição direta.',
      ],
      mistakes: [
        'Descartar resíduo sem verificar a meia-vida.',
        'Misturar com resíduos do Grupo A.',
        'Falta de identificação de data de entrada.',
      ],
      summary: [
        { attribute: 'Identificação', specification: 'Símbolo internacional de radiação ionizante em rótulo de fundo amarelo, com a expressão MATERIAL RADIOATIVO, REJEITO RADIOATIVO ou RADIOATIVO.', term: 'Anexo II - Grupo C' },
        { attribute: 'Norma aplicável', specification: 'O gerenciamento deve obedecer ao Plano de Proteção Radiológica do serviço, às normas da CNEN e demais normas aplicáveis.', term: 'Art. 33' },
        { attribute: 'Acondicionamento', specification: 'Procedimentos definidos pelo supervisor de proteção radiológica qualificado pela CNEN; recipientes adequados às características físicas, químicas, biológicas e radiológicas, com vedação e identificação.', term: 'Arts. 20 e 73' },
        { attribute: 'Segregação', specification: 'Segregar de acordo com radionuclídeo ou natureza da radiação, estado físico, concentração e taxa de exposição.', term: 'Art. 72' },
        { attribute: 'Riscos associados', specification: 'RSS químico radioativo deve identificar risco radiológico e químico; perfurocortante radioativo deve ser transportado para decaimento em recipiente blindado, sem reencape ou separação manual.', term: 'Arts. 74 e 75' },
        { attribute: 'Decaimento', specification: 'Armazenar em condições adequadas para decaimento, na área de manipulação ou em sala identificada como SALA DE DECAIMENTO; líquidos exigem contenção adequada.', term: 'Art. 76' },
        { attribute: 'Liberação', specification: 'Ao atingir o limite de dispensa, retirar o rótulo de rejeito radioativo apenas após medição da radiação, mantendo a identificação dos demais riscos presentes.', term: 'Art. 79' },
      ],
      practicalTip: 'O manejo do Grupo C deve ser definido pelo supervisor de proteção radiológica: separar por radionuclídeo, registrar entrada e liberar apenas após medição e limite de dispensa.',
    },
    D: {
      id: 'D',
      title: 'Grupo D: Resíduos Comuns',
      subtitle: 'Resíduos Comuns',
      description: 'Resíduos que não apresentam risco biológico, químico ou radiológico. Similares aos resíduos domésticos.',
      examples: [
        { label: 'Papel e Papelão', description: 'Não contaminados: papéis e embalagens.', icon: 'FileText' },
        { label: 'Restos de Alimentos', description: 'Copa, recepção e áreas administrativas.', icon: 'Utensils' },
        { label: 'Papel Esterilizado', description: 'Embalagens de papel esterilizado limpas.', icon: 'ShieldCheck' },
        { label: 'Plásticos Limpos', description: 'Copos e garrafas não utilizados na assistência.', icon: 'GlassWater' },
      ],
      disposal: {
        instructions: 'Acondicionar conforme as orientações do serviço de limpeza urbana e do PGRSS. Resíduos recicláveis limpos devem seguir a coleta seletiva definida pela unidade.',
        container: 'Coletor conforme PGRSS',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      },
      risks: [
        'Contaminação do Reciclável: Misturar com lixo orgânico.',
        'Desperdício: Descartar resíduo infectante como comum.',
      ],
      mistakes: [
        'Misturar lixo orgânico com material reciclável.',
        'Descartar luvas ou gazes contaminadas no Grupo D.',
      ],
      summary: [
        { attribute: 'Identificação', specification: 'Identificação conforme definido pelo órgão de limpeza urbana; os sacos que acondicionam RSS do Grupo D não precisam ser identificados.', term: 'Anexo II e Art. 22, §1º' },
        { attribute: 'Acondicionamento', specification: 'Acondicionar de acordo com as orientações dos órgãos locais responsáveis pelo serviço de limpeza urbana.', term: 'Art. 21' },
        { attribute: 'Rejeitos', specification: 'Quando não encaminhados para reutilização, recuperação, reciclagem, compostagem, logística reversa ou aproveitamento energético, os RSS do Grupo D são classificados como rejeitos.', term: 'Art. 80' },
        { attribute: 'Reciclagem', specification: 'Procedimentos de segregação, acondicionamento e identificação dos coletores para reciclagem devem estar descritos no PGRSS.', term: 'Art. 83' },
        { attribute: 'Compostagem', specification: 'Podem seguir para compostagem apenas os resíduos orgânicos permitidos, como sobras de alimentos, podas, jardinagem e forrações de animais de biotérios sem risco biológico associado.', term: 'Art. 84' },
        { attribute: 'Critério de grupo', specification: 'Materiais sem sinais ou suspeita de contaminação química, biológica ou radiológica podem ter manejo como Grupo D.', term: 'Art. 82' },
      ],
      practicalTip: 'Papel toalha de banheiros e pia de lavagem de mãos é Grupo D.',
    },
    E: {
      id: 'E',
      title: 'Grupo E: Perfurocortantes',
      subtitle: 'Perfurocortantes',
      description: 'Materiais perfurocortantes ou escarificantes, como agulhas, lâminas de bisturi, ampolas de vidro e escalpes.',
      examples: [
        { label: 'Agulhas e Seringas', description: 'Todo material perfurante usado ou não.', icon: 'Syringe' },
        { label: 'Lâminas de Bisturi', description: 'Materiais de corte cirúrgico.', icon: 'Scissors' },
        { label: 'Ampolas de Vidro', description: 'Frascos e ampolas que podem quebrar.', icon: 'FlaskRound' },
        { label: 'Escalpes e Lancetas', description: 'Materiais de punção capilar e venosa.', icon: 'Zap' },
      ],
      disposal: {
        instructions: 'Descartar imediatamente em recipiente identificado, rígido, com tampa, resistente à punctura, ruptura e vazamento. Não esvaziar nem reaproveitar o coletor.',
        container: 'Coletor Rígido de Perfurocortantes',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      },
      risks: [
        'Acidente Percutâneo: Risco de transmissão de HIV e Hepatites.',
        'Perfuração de Sacos: Risco para a equipe de limpeza.',
      ],
      mistakes: [
        'Reencapar agulhas antes de descartar.',
        'Descartar agulhas em sacos plásticos.',
        'Ultrapassar 3/4 da capacidade ou o limite indicado pelo fabricante.',
      ],
      summary: [
        { attribute: 'Identificação', specification: 'Símbolo de risco biológico em rótulo de fundo branco, desenho e contorno preto, acrescido da inscrição RESÍDUO PERFUROCORTANTE ou PERFUROCORTANTE.', term: 'Anexo II - Grupo E' },
        { attribute: 'Acondicionamento', specification: 'Descartar em recipientes identificados, rígidos, providos com tampa, resistentes à punctura, ruptura e vazamento.', term: 'Art. 86' },
        { attribute: 'Limite de uso', specification: 'Substituir conforme demanda, ao atingir 3/4 da capacidade ou conforme instruções do fabricante; é proibido esvaziamento manual e reaproveitamento.', term: 'Art. 87' },
        { attribute: 'Risco associado', specification: 'Quando contaminados por agentes biológicos, químicos ou substâncias radioativas, o manejo deve seguir cada classe de risco associada e o recipiente deve indicar todos os riscos presentes.', term: 'Art. 88' },
        { attribute: 'Sem risco adicional', specification: 'Seringas, agulhas e demais perfurocortantes sem risco químico, biológico ou radiológico não necessitam de tratamento prévio antes da disposição final ambientalmente adequada.', term: 'Art. 89' },
        { attribute: 'Segurança', specification: 'É vedado reencape manual e desconexão manual de agulhas; separação do conjunto seringa-agulha só é permitida com dispositivo de segurança.', term: 'Art. 89' },
      ],
      practicalTip: 'Nunca reencape agulhas. Descarte imediatamente após o uso no coletor rígido mais próximo.',
    },
  },
  en: {
    A: {
      id: 'A',
      title: 'Group A: Biological Hazard',
      subtitle: 'Infectious Waste',
      description: 'Waste with the possible presence of biological agents that, due to their higher virulence or concentration, may present a risk of infection.',
      examples: [
        { label: 'Blood-Stained Gloves', description: 'Gloves stained with blood used during procedures.', icon: 'Droplets' },
        { label: 'Gauze and Dressings', description: 'Gauze and dressings from open wounds.', icon: 'Bandage' },
        { label: 'Transfusion Bags', description: 'Empty or expired blood transfusion bags.', icon: 'HeartPulse' },
        { label: 'Culture Media', description: 'Laboratory culture media and inoculated plates.', icon: 'Microscope' },
      ],
      disposal: {
        instructions: 'Segregate by subgroup: red bag when treatment is mandatory; milky white bag for waste that does not require treatment or after treatment, according to the PGRSS.',
        container: 'White/Red Bag',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      },
      risks: [
        'Exposure to pathogens such as HIV and Hepatitis (B and C).',
        'Cross-contamination in sterile environments.',
      ],
      mistakes: [
        'Discarding clean paper towels in the white bag.',
        'Mixing sharps (Group E) into the infectious waste bag.',
      ],
      summary: [
        { attribute: 'Identification', specification: 'Biohazard symbol on a white-background label, with black drawing and outline, plus the wording INFECTIOUS WASTE.', term: 'Annex II - Group A' },
        { attribute: 'Packaging', specification: 'Bag made of rupture-resistant, leak-resistant and impermeable material; milky white bag for waste that does not require mandatory treatment or after treatment.', term: 'Arts. 13 and 15' },
        { attribute: 'Mandatory treatment', specification: 'When treatment is required, use a red bag; subgroup A5 must be segregated in a double red bag and sent for incineration.', term: 'Arts. 16 and 55' },
        { attribute: 'Use limit', specification: 'Replace the bag at 2/3 capacity or every 48 hours; easily putrescible waste must be replaced within 24 hours.', term: 'Art. 14' },
        { attribute: 'Destination', specification: 'Treated waste or waste that does not require treatment must go to environmentally appropriate final disposal under applicable licensing.', term: 'Art. 15' },
      ],
      practicalTip: 'When in doubt, check for free-flowing blood or body fluids, suspected biological contamination, or classification in subgroups A1 to A5 before discarding as Group A.',
    },
    B: {
      id: 'B',
      title: 'Group B: Chemical Waste',
      subtitle: 'Chemical Waste',
      description: 'Chemical substances that present a risk to public health or the environment due to their flammability, corrosivity, reactivity, or toxicity.',
      examples: [
        { label: 'Organic Solvents', description: 'Flammable: Amber glass or HDPE bottle.', icon: 'FlaskConical' },
        { label: 'Sulfuric Acid', description: 'Corrosive: Container resistant to strong acids.', icon: 'TestTubeDiagonal' },
        { label: 'Expired Medicines', description: 'Toxic: original packaging or compatible identified container.', icon: 'Pill' },
        { label: 'Heavy Metals', description: 'Persistent: Hermetic sealing mandatory.', icon: 'Skull' },
      ],
      disposal: {
        instructions: 'Use a container compatible with the chemical product, resistant, leak-proof when liquid, and identified with risk symbol and phrase. Incompatible waste must remain separated.',
        container: 'Compatible Identified Container',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      },
      risks: [
        'Chemical Burns: Serious injuries from direct contact with acids or bases.',
        'Environmental Contamination: Irreversible damage to groundwater and local fauna.',
      ],
      mistakes: [
        'Discarding liquids in common sinks.',
        'Mixing incompatible substances.',
        'Omitting identification on the container.',
      ],
      summary: [
        { attribute: 'Identification', specification: 'Symbol and risk phrase associated with the chemical waste hazard; GHS symbols and phrases may be used according to the risk.', term: 'Annex II - Group B' },
        { attribute: 'Liquid packaging', specification: 'Container compatible with the liquid, resistant, rigid, leak-proof, with a lid that ensures containment and identification.', term: 'Art. 18' },
        { attribute: 'Solid packaging', specification: 'Rigid, resistant container compatible with the characteristics of the chemical product and properly identified.', term: 'Art. 19' },
        { attribute: 'Segregation', specification: 'Incompatible chemicals or different categories must be segregated, packaged and identified separately.', term: 'Annexes III and IV' },
        { attribute: 'Treatment and destination', specification: 'Hazardous liquid chemical waste must be treated before final disposal; hazardous solid rejects go to Class I hazardous waste landfill.', term: 'Arts. 57 and 58' },
      ],
      practicalTip: 'All chemical waste must be properly labeled with the substance name, date, and responsible person.',
    },
    C: {
      id: 'C',
      title: 'Group C: Radioactive Waste',
      subtitle: 'Radioactive Waste',
      description: 'Materials containing radionuclides in quantities exceeding the clearance limits established by CNEN.',
      examples: [
        { label: 'Nuclear Medicine', description: 'Nuclear Medicine and Radiotherapy services.', icon: 'Radiation' },
        { label: 'Research', description: 'Research labs using Radioisotopes.', icon: 'Microscope' },
        { label: 'Body Fluids', description: 'Body fluids from patients under treatment.', icon: 'Droplets' },
        { label: 'Contaminated', description: 'Contaminated needles, syringes, and gloves.', icon: 'Biohazard' },
      ],
      disposal: {
        instructions: 'Follow the Radiation Protection Plan and CNEN standards; store for decay under adequate conditions, with shielding when indicated by the radiation protection supervisor.',
        container: 'Container Defined by PPR/CNEN',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      },
      risks: [
        'Ionizing Radiation: Cellular damage and genetic mutations.',
        'Radiological Burns: Severe injuries from direct exposure.',
      ],
      mistakes: [
        'Discarding waste without checking half-life.',
        'Mixing with Group A waste.',
        'Lack of entry date identification.',
      ],
      summary: [
        { attribute: 'Identification', specification: 'International ionizing radiation symbol on a yellow-background label, with the wording RADIOACTIVE MATERIAL, RADIOACTIVE REJECT or RADIOACTIVE.', term: 'Annex II - Group C' },
        { attribute: 'Packaging', specification: 'Procedures defined by a radiation protection supervisor qualified by CNEN; containers suited to the physical, chemical, biological and radiological characteristics.', term: 'Arts. 20 and 73' },
        { attribute: 'Segregation', specification: 'Segregate by radionuclide or nature of radiation, physical state, concentration and exposure rate.', term: 'Art. 72' },
        { attribute: 'Decay', specification: 'Store under suitable conditions for decay, in the handling area or in a specific room identified as DECAY ROOM.', term: 'Art. 76' },
        { attribute: 'Reclassification', specification: 'After reaching the clearance level, remove radiological-risk identification after measurement and classify by remaining risk.', term: 'Art. 79' },
      ],
      practicalTip: 'Group C management must be defined by the radiation protection supervisor: segregate by radionuclide, record entry, and release only after measurement and clearance level confirmation.',
    },
    D: {
      id: 'D',
      title: 'Group D: General Waste',
      subtitle: 'General Waste',
      description: 'Waste that does not present a biological, chemical, or radiological risk. Similar to household waste.',
      examples: [
        { label: 'Paper and Cardboard', description: 'Non-contaminated: papers and packaging.', icon: 'FileText' },
        { label: 'Food Scraps', description: 'Kitchen, reception, and administrative areas.', icon: 'Utensils' },
        { label: 'Sterile Paper', description: 'Clean sterile paper packaging.', icon: 'ShieldCheck' },
        { label: 'Clean Plastics', description: 'Cups and bottles not used in care.', icon: 'GlassWater' },
      ],
      disposal: {
        instructions: 'Package according to local urban cleaning guidance and the PGRSS. Clean recyclable waste must follow the selective collection procedure defined by the facility.',
        container: 'Collector Defined by PGRSS',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      },
      risks: [
        'Recyclable Contamination: Mixing with organic waste.',
        'Wastefulness: Discarding infectious waste as common.',
      ],
      mistakes: [
        'Mixing organic waste with recyclable material.',
        'Discarding contaminated gloves or gauze in Group D.',
      ],
      summary: [
        { attribute: 'Identification', specification: 'Identification as defined by the local urban cleaning authority; bags holding Group D waste do not need identification.', term: 'Annex II and Art. 22, §1' },
        { attribute: 'Packaging', specification: 'Package according to the guidance of local bodies responsible for urban cleaning services.', term: 'Art. 21' },
        { attribute: 'Recycling', specification: 'Segregation, packaging and collector identification procedures for recycling must be described in the PGRSS.', term: 'Art. 83' },
        { attribute: 'Composting', specification: 'Only permitted organic waste may go to composting, such as food leftovers and animal bedding without associated biological risk.', term: 'Art. 84' },
        { attribute: 'Group criterion', specification: 'Materials without signs or suspicion of chemical, biological or radiological contamination may be managed as Group D.', term: 'Art. 82' },
      ],
      practicalTip: 'Bathroom and hand-washing paper towels are Group D when there is no sign or suspicion of biological, chemical, or radiological contamination.',
    },
    E: {
      id: 'E',
      title: 'Group E: Sharps',
      subtitle: 'Sharps Waste',
      description: 'Sharps or cutting materials, such as needles, scalpel blades, glass ampoules, and lancets.',
      examples: [
        { label: 'Needles and Syringes', description: 'All piercing material used or not.', icon: 'Syringe' },
        { label: 'Scalpel Blades', description: 'Surgical cutting materials.', icon: 'Scissors' },
        { label: 'Glass Ampoules', description: 'Flasks and ampoules that can break.', icon: 'FlaskRound' },
        { label: 'Lancets', description: 'Capillary and venous puncture materials.', icon: 'Zap' },
      ],
      disposal: {
        instructions: 'Discard immediately in an identified rigid container with lid, resistant to puncture, rupture, and leakage. Do not empty or reuse the container.',
        container: 'Sharps Container',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      },
      risks: [
        'Percutaneous Accident: Risk of HIV and Hepatitis transmission.',
        'Bag Puncture: Risk for cleaning staff.',
      ],
      mistakes: [
        'Recapping needles before discarding.',
        'Discarding needles in plastic bags.',
        'Exceeding 3/4 capacity or the limit indicated by the manufacturer.',
      ],
      summary: [
        { attribute: 'Identification', specification: 'Biohazard symbol on a white-background label, with black drawing and outline, plus the wording SHARPS WASTE or SHARPS.', term: 'Annex II - Group E' },
        { attribute: 'Packaging', specification: 'Dispose in identified, rigid containers with lid, resistant to puncture, rupture and leakage.', term: 'Art. 86' },
        { attribute: 'Use limit', specification: 'Replace according to demand, at 3/4 capacity or according to manufacturer instructions; manual emptying and reuse are prohibited.', term: 'Art. 87' },
        { attribute: 'Associated risk', specification: 'When contaminated by biological agents, chemicals or radioactive substances, management must follow each associated risk class.', term: 'Art. 88' },
        { attribute: 'Safety', specification: 'Dispose immediately after use, without manual needle recapping or separation of contaminated assemblies when associated risk exists.', term: 'RDC 222/2018' },
      ],
      practicalTip: 'Never recap needles. Discard immediately after use in the nearest rigid collector.',
    },
  },
  es: {
    A: {
      id: 'A',
      title: 'Grupo A: Peligro Biológico',
      subtitle: 'Residuos Infectantes',
      description: 'Residuos con posible presencia de agentes biológicos que, por sus características de mayor virulencia o concentración, pueden presentar riesgo de infección.',
      examples: [
        { label: 'Guantes con Sangre', description: 'Guantes manchados con sangre usados durante procedimientos.', icon: 'Droplets' },
        { label: 'Gasas y Vendajes', description: 'Gasas y vendajes de heridas abiertas.', icon: 'Bandage' },
        { label: 'Bolsas de Transfusión', description: 'Bolsas de transfusión sanguínea vacías o caducadas.', icon: 'HeartPulse' },
        { label: 'Medios de Cultivo', description: 'Medios de cultivo de laboratorio y placas inoculadas.', icon: 'Microscope' },
      ],
      disposal: {
        instructions: 'Segregar conforme al subgrupo: bolsa roja cuando exista tratamiento obligatorio; bolsa blanca lechosa para residuos que no requieren tratamiento previo o después del tratamiento, según el PGRSS.',
        container: 'Bolsa blanca lechosa o roja',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      },
      risks: [
        'Exposición a patógenos como VIH y Hepatitis (B y C).',
        'Contaminación cruzada en ambientes estériles.',
      ],
      mistakes: [
        'Desechar toallas de papel limpias en la bolsa blanca.',
        'Mezclar punzocortantes (Grupo E) en la bolsa de residuos infectantes.',
      ],
      summary: [
        { attribute: 'Identificación', specification: 'Símbolo de riesgo biológico en etiqueta de fondo blanco, dibujo y contornos negros, con la expresión RESIDUO INFECTANTE.', term: 'Anexo II - Grupo A' },
        { attribute: 'Bolsa y recolector', specification: 'Los RSS sólidos deben acondicionarse en bolsa resistente a ruptura, fuga e impermeable; el recolector debe ser lavable, resistente a punción, ruptura, fuga y vuelco, con tapa sin contacto manual cuando corresponda.', term: 'Arts. 13 y 17' },
        { attribute: 'Tratamiento obligatorio', specification: 'Cuando exista obligación de tratamiento, se debe usar bolsa roja; el subgrupo A5 debe segregarse en bolsa roja doble, en recipiente exclusivo identificado, y enviarse a incineración.', term: 'Arts. 16 y 55' },
        { attribute: 'Límite de uso', specification: 'Sustituir la bolsa al alcanzar 2/3 de la capacidad o cada 48 horas; residuos fácilmente putrescibles deben sustituirse en hasta 24 horas.', term: 'Art. 14' },
        { attribute: 'Destino', specification: 'Los residuos tratados o que no requieren tratamiento deben ir a disposición final ambientalmente adecuada según la licencia aplicable.', term: 'Art. 15' },
      ],
      practicalTip: 'Ante la duda, verifique si hay sangre o líquidos corporales libres, sospecha de contaminación biológica o encuadre en los subgrupos A1 a A5 antes de clasificar como Grupo A.',
    },
    B: {
      id: 'B',
      title: 'Grupo B: Residuos Químicos',
      subtitle: 'Residuos Químicos',
      description: 'Sustancias químicas que presentan riesgo para la salud pública o el medio ambiente por sus características de inflamabilidad, corrosividad, reactividad o toxicidad.',
      examples: [
        { label: 'Solventes Orgánicos', description: 'Inflamable: Frasco de vidrio ámbar o HDPE.', icon: 'FlaskConical' },
        { label: 'Ácido Sulfúrico', description: 'Corrosivo: Contenedor resistente a ácidos fuertes.', icon: 'TestTubeDiagonal' },
        { label: 'Medicamentos vencidos', description: 'Tóxico: envase original o recipiente compatible identificado.', icon: 'Pill' },
        { label: 'Metales Pesados', description: 'Persistente: Sellado hermético obligatorio.', icon: 'Skull' },
      ],
      disposal: {
        instructions: 'Utilizar recipiente compatible con el producto químico, resistente, estanco cuando sea líquido e identificado con símbolo y frase de riesgo. Los residuos incompatibles deben permanecer separados.',
        container: 'Recipiente compatible identificado',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      },
      risks: [
        'Quemaduras Químicas: Lesiones graves por contacto directo con ácidos o bases.',
        'Contaminación Ambiental: Daños irreversibles a aguas subterráneas y fauna local.',
      ],
      mistakes: [
        'Desechar líquidos en fregaderos comunes.',
        'Mezclar sustancias incompatibles.',
        'Omitir la identificación en el contenedor.',
      ],
      summary: [
        { attribute: 'Identificación', specification: 'Símbolo y frase de riesgo asociados a la peligrosidad del residuo químico; pueden usarse símbolos y frases GHS según el riesgo.', term: 'Anexo II - Grupo B' },
        { attribute: 'Acondicionamiento líquido', specification: 'Recipiente compatible con el líquido, resistente, rígido, estanco, con tapa que garantice contención e identificación.', term: 'Art. 18' },
        { attribute: 'Acondicionamiento sólido', specification: 'Recipiente rígido, resistente, compatible con las características del producto químico acondicionado e identificado.', term: 'Art. 19' },
        { attribute: 'Segregación', specification: 'Sustancias químicas incompatibles o de categorías distintas deben segregarse, acondicionarse e identificarse por separado.', term: 'Anexos III y IV' },
        { attribute: 'Tratamiento y destino', specification: 'Los RSS químicos peligrosos líquidos deben tratarse antes de la disposición final; está prohibido enviar líquidos a relleno sanitario. Los residuos sólidos peligrosos siguen a relleno Clase I.', term: 'Arts. 57 y 58' },
      ],
      practicalTip: 'Todo residuo químico debe estar identificado con el nombre de la sustancia, el riesgo, la fecha y el responsable, según el PGRSS.',
    },
    C: {
      id: 'C',
      title: 'Grupo C: Residuos Radiactivos',
      subtitle: 'Residuos Radiactivos',
      description: 'Materiales que contienen radionúclidos en cantidades superiores a los límites de exención definidos por la Comisión Nacional de Energía Nuclear (CNEN).',
      examples: [
        { label: 'Medicina Nuclear', description: 'Servicios de Medicina Nuclear y Radioterapia.', icon: 'Radiation' },
        { label: 'Investigación', description: 'Laboratorios de investigación que usan radioisótopos.', icon: 'Microscope' },
        { label: 'Fluidos corporales', description: 'Fluidos corporales de pacientes en tratamiento con radionúclidos.', icon: 'Droplets' },
        { label: 'Materiales contaminados', description: 'Agujas, jeringas y guantes con contaminación radioactiva.', icon: 'Biohazard' },
      ],
      disposal: {
        instructions: 'Seguir el Plan de Protección Radiológica y las normas de la CNEN; almacenar para decaimiento en condiciones adecuadas, con blindaje cuando sea indicado por el supervisor de protección radiológica.',
        container: 'Recipiente definido por PPR/CNEN',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      },
      risks: [
        'Radiación Ionizante: Daños celulares y mutaciones genéticas.',
        'Quemaduras Radiológicas: Lesiones graves por exposición directa.',
      ],
      mistakes: [
        'Desechar residuos sin verificar la vida media.',
        'Mezclar con residuos del Grupo A.',
        'Falta de identificación de la fecha de entrada.',
      ],
      summary: [
        { attribute: 'Identificación', specification: 'Símbolo internacional de radiación ionizante en etiqueta de fondo amarillo, con la expresión MATERIAL RADIOACTIVO, RECHAZO RADIOACTIVO o RADIOACTIVO.', term: 'Anexo II - Grupo C' },
        { attribute: 'Norma aplicable', specification: 'El manejo debe obedecer al Plan de Protección Radiológica del servicio, a las normas de la CNEN y a las demás normas aplicables.', term: 'Art. 33' },
        { attribute: 'Acondicionamiento', specification: 'Procedimientos definidos por supervisor de protección radiológica calificado por la CNEN; recipientes adecuados a las características físicas, químicas, biológicas y radiológicas, con cierre e identificación.', term: 'Arts. 20 y 73' },
        { attribute: 'Segregación', specification: 'Segregar según radionúclido o naturaleza de la radiación, estado físico, concentración y tasa de exposición.', term: 'Art. 72' },
        { attribute: 'Decaimiento', specification: 'Almacenar en condiciones adecuadas para decaimiento, en el área de manipulación o en sala específica identificada como SALA DE DECAIMIENTO.', term: 'Art. 76' },
        { attribute: 'Reclasificación', specification: 'Tras alcanzar el límite de dispensa, retirar la identificación de riesgo radiológico mediante medición y clasificar según el riesgo remanente.', term: 'Art. 79' },
      ],
      practicalTip: 'El manejo del Grupo C debe ser definido por el supervisor de protección radiológica: separar por radionúclido, registrar la entrada y liberar solo después de medición y límite de dispensa.',
    },
    D: {
      id: 'D',
      title: 'Grupo D: Residuos Comunes',
      subtitle: 'Residuos Comunes',
      description: 'Residuos que no presentan un riesgo biológico, químico o radiológico. Similares a los residuos domésticos.',
      examples: [
        { label: 'Papel y Cartón', description: 'No contaminados: papeles y envases.', icon: 'FileText' },
        { label: 'Restos de Comida', description: 'Cocina, recepción y áreas administrativas.', icon: 'Utensils' },
        { label: 'Papel Estéril', description: 'Envases de papel estéril limpios.', icon: 'ShieldCheck' },
        { label: 'Plásticos Limpios', description: 'Vasos y botellas no utilizados en la asistencia.', icon: 'GlassWater' },
      ],
      disposal: {
        instructions: 'Acondicionar según las orientaciones del servicio de limpieza urbana y del PGRSS. Los residuos reciclables limpios deben seguir la recolección selectiva definida por la unidad.',
        container: 'Recolector conforme al PGRSS',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      },
      risks: [
        'Contaminación de Reciclables: Mezclar con residuos orgánicos.',
        'Desperdicio: Desechar residuos infectantes como comunes.',
      ],
      mistakes: [
        'Mezclar residuos orgánicos con material reciclable.',
        'Desechar guantes o gasas contaminadas en el Grupo D.',
      ],
      summary: [
        { attribute: 'Identificación', specification: 'Identificación conforme lo definido por el órgano de limpieza urbana; las bolsas que acondicionan residuos del Grupo D no necesitan identificación.', term: 'Anexo II y Art. 22, §1º' },
        { attribute: 'Acondicionamiento', specification: 'Acondicionar de acuerdo con las orientaciones de los órganos locales responsables del servicio de limpieza urbana.', term: 'Art. 21' },
        { attribute: 'Reciclaje', specification: 'Los procedimientos de segregación, acondicionamiento e identificación de colectores para reciclaje deben estar descritos en el PGRSS.', term: 'Art. 83' },
        { attribute: 'Compostaje', specification: 'Solo residuos orgánicos permitidos pueden ir a compostaje, como sobras de alimentos y forrajes sin riesgo biológico asociado.', term: 'Art. 84' },
        { attribute: 'Criterio de grupo', specification: 'Materiales sin señales o sospecha de contaminación química, biológica o radiológica pueden manejarse como Grupo D.', term: 'Art. 82' },
      ],
      practicalTip: 'Las toallas de papel de baños y lavabos, sin contaminación biológica, química o radiológica, se manejan como Grupo D.',
    },
    E: {
      id: 'E',
      title: 'Grupo E: Punzocortantes',
      subtitle: 'Residuos Punzocortantes',
      description: 'Materiales punzocortantes o escarificantes, como agujas, hojas de bisturí, ampollas de vidrio y lancetas.',
      examples: [
        { label: 'Agujas y Jeringas', description: 'Todo material punzante usado o no.', icon: 'Syringe' },
        { label: 'Hojas de Bisturí', description: 'Materiales de corte quirúrgico.', icon: 'Scissors' },
        { label: 'Ampollas de Vidrio', description: 'Frascos y ampollas que pueden romperse.', icon: 'FlaskRound' },
        { label: 'Lancetas', description: 'Materiales de punción capilar y venosa.', icon: 'Zap' },
      ],
      disposal: {
        instructions: 'Descartar inmediatamente en recipiente identificado, rígido, con tapa y resistente a punción, ruptura y fuga. No vaciar ni reutilizar el recolector.',
        container: 'Recolector rígido para punzocortantes',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      },
      risks: [
        'Accidente Percutáneo: Riesgo de transmisión de VIH y Hepatitis.',
        'Perforación de Bolsas: Riesgo para el personal de limpieza.',
      ],
      mistakes: [
        'Reencapuchar agujas antes de desecharlas.',
        'Desechar agujas en bolsas de plástico.',
        'Superar 3/4 de la capacidad o el límite indicado por el fabricante.',
      ],
      summary: [
        { attribute: 'Identificación', specification: 'Símbolo de riesgo biológico en etiqueta de fondo blanco, dibujo y contorno negro, con la inscripción RESIDUO PUNZOCORTANTE o PUNZOCORTANTE.', term: 'Anexo II - Grupo E' },
        { attribute: 'Acondicionamiento', specification: 'Descartar en recipientes identificados, rígidos, con tapa, resistentes a punción, ruptura y fuga.', term: 'Art. 86' },
        { attribute: 'Límite de uso', specification: 'Sustituir según demanda, al alcanzar 3/4 de la capacidad o según instrucciones del fabricante; se prohíbe vaciado manual y reutilización.', term: 'Art. 87' },
        { attribute: 'Riesgo asociado', specification: 'Cuando estén contaminados por agentes biológicos, químicos o sustancias radioactivas, el manejo debe seguir cada clase de riesgo asociada.', term: 'Art. 88' },
        { attribute: 'Seguridad', specification: 'El descarte debe ocurrir inmediatamente después del uso, sin reencapuchar agujas ni separar conjuntos contaminados cuando exista riesgo asociado.', term: 'RDC 222/2018' },
      ],
      practicalTip: 'Nunca reencapuche agujas. Deséchelas inmediatamente después del uso en el recolector rígido más cercano.',
    },
  },
};

export const SCENARIOS: Record<Language, Scenario[]> = {
  pt: [
    {
      id: 'samu',
      title: 'Atendimento SAMU',
      category: 'Emergência Extra-hospitalar',
      sector: 'SAMU',
      groups: ['E'],
      reference: 'RDC 222/2018, Arts. 86 a 89',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM6x_dPnnP5fi0MxCat9ErVsTA5RkAYFhUeDIRMKpCQuX7L6QiMaAHY8K2-XqTzIPo8UqFyOrN3KJF_ThJRRWvRLB2VMXPKxHv3TRuRnhu9bDcpRK6vmDdI5q70I7J5E46BsqYUAqNJMEtiSxK-ywVz7SODbGOsBO4cof8_wOwuSlLnXPfKbgJ6MgMvF5YQ3Zf38kbBRk0oJ52GXrzWkbMwN0mRwoB-NxMyVTWN2F5ehTNGdLycPIXg4Ok3bTUEeEwDIyiOmWHTBFj',
      wrong: 'Descartar agulhas de acesso venoso no lixo comum ou sacos plásticos infectantes dentro da viatura.',
      right: 'Descartar imediatamente em coletor rígido, identificado, com tampa e resistente à punctura, ruptura e vazamento.',
    },
    {
      id: 'uti',
      title: 'Troca de Sonda na UTI',
      category: 'Unidade de Terapia Intensiva',
      sector: 'UTI',
      groups: ['A', 'D'],
      reference: 'RDC 222/2018, Anexo I - Grupos A/D e Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Descartar o invólucro plástico limpo no saco branco de infectantes.',
      right: 'Descarte a sonda conforme risco biológico e PGRSS, normalmente no fluxo do Grupo A quando houver secreções ou líquidos corpóreos. O invólucro limpo vai para o Grupo D.',
      attention: 'Lixeiras devem ser acionadas por pedal.',
    },
    {
      id: 'cc',
      title: 'Centro Cirúrgico',
      category: 'Pós-Operatório',
      sector: 'Centro Cirúrgico',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Grupo A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1qvjiKgaA2i7XucKzr1OUphoL_HgQoPGfY5KyfNwOLpPg757zrcdnvr5U-WtpEtpjrGnnYdmcY1BfulQzU_Wd9CEDHqQhxzU-LwKzzYxxkM97d0ZUSIdri65yRpHj0Ws1fxM-5w2TORPDBes_iTwoLZ3kcusdpJV2wk-gAIObmJC1u941iWzOwYBRmcX4K0IcLKM3HCQUtqImPb1c-tgGWfvoYoTVnVuXAaFvnbYfQXNceHDD_AsVzxZRhkygDhbYaJ9xLC3yU0zy',
      wrong: 'Encaminhar peças anatômicas (tecidos) para o lixo infectante comum.',
      right: 'Peças anatômicas devem seguir o fluxo específico do Grupo A/subgrupo aplicável, com identificação, acondicionamento e destinação definidos no PGRSS.',
    },
    {
      id: 'curativo-sangue',
      title: 'Curativo com sangue',
      category: 'Sala de Curativos',
      sector: 'Curativos',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Grupo A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Jogar gaze ou curativo com sangue no lixo comum por parecer material pequeno.',
      right: 'Se houver sangue ou líquido corpóreo na forma livre, classificar pelo risco biológico e seguir o fluxo do Grupo A no PGRSS.',
    },
    {
      id: 'luva-limpa',
      title: 'Luva sem contaminação',
      category: 'Procedimento sem secreção',
      sector: 'Ambulatório',
      groups: ['D'],
      reference: 'RDC 222/2018, Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Descartar toda luva usada na assistência automaticamente como infectante.',
      right: 'Luvas sem sinais ou suspeita de contaminação biológica, química ou radiológica podem ser manejadas como Grupo D.',
    },
    {
      id: 'placa-petri',
      title: 'Placa de Petri com cultura',
      category: 'Laboratório',
      sector: 'Laboratório',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Subgrupo A1 e Art. 16',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Enviar placa inoculada diretamente para coleta externa em saco branco.',
      right: 'Culturas e meios de cultura pertencem ao subgrupo A1 e devem seguir tratamento/fluxo definido antes de sair da unidade, conforme PGRSS.',
    },
    {
      id: 'medicamento-vencido',
      title: 'Medicamento vencido',
      category: 'Farmácia',
      sector: 'Farmácia',
      groups: ['B'],
      reference: 'RDC 222/2018, Anexo I - Grupo B e Art. 59',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Descartar medicamentos vencidos em lixeira comum ou pia.',
      right: 'Classificar como Grupo B quando houver risco químico e seguir tratamento, logística ou destinação prevista no PGRSS e licenciamento.',
    },
    {
      id: 'quimicos-incompativeis',
      title: 'Mistura de reagentes',
      category: 'Laboratório Químico',
      sector: 'Laboratório',
      groups: ['B'],
      reference: 'RDC 222/2018, Art. 60 e Anexos III/IV',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Misturar sobras químicas diferentes no mesmo frasco para economizar espaço.',
      right: 'Resíduos químicos incompatíveis devem ser segregados, acondicionados e identificados separadamente conforme risco e compatibilidade.',
    },
    {
      id: 'termometro-mercurio',
      title: 'Termômetro com mercúrio quebrado',
      category: 'Acidente no Setor',
      sector: 'Laboratório',
      groups: ['B', 'E'],
      reference: 'RDC 222/2018, Anexo I - Grupo B e Art. 88',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Juntar o vidro com papel e descartar como lixo comum.',
      right: 'Há risco químico pelo mercúrio e risco perfurocortante pelo vidro. O recipiente deve conter identificação de todos os riscos presentes.',
    },
    {
      id: 'coletor-34',
      title: 'Coletor de perfurocortante cheio',
      category: 'Posto de Enfermagem',
      sector: 'Enfermagem',
      groups: ['E'],
      reference: 'RDC 222/2018, Art. 87',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Compactar ou chacoalhar o coletor para caber mais material.',
      right: 'Substituir conforme demanda, ao atingir 3/4 da capacidade ou conforme fabricante. É proibido esvaziar manualmente e reaproveitar.',
    },
    {
      id: 'resto-isolamento',
      title: 'Resto alimentar de paciente em isolamento',
      category: 'Copa Hospitalar',
      sector: 'Refeitório',
      groups: ['D', 'A'],
      reference: 'RDC 222/2018, Art. 84 e avaliação de risco do PGRSS',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Enviar automaticamente para compostagem sem verificar isolamento ou risco associado.',
      right: 'Compostagem só é permitida para restos alimentares de pacientes que não estejam em isolamento. Em isolamento, seguir avaliação de risco e PGRSS.',
    },
    {
      id: 'radioiodo',
      title: 'Paciente em terapia com iodo-131',
      category: 'Medicina Nuclear',
      sector: 'Medicina Nuclear',
      groups: ['C'],
      reference: 'RDC 222/2018, Arts. 33, 76 a 79',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Retirar a identificação radioativa antes de medir o nível de radiação.',
      right: 'Armazenar para decaimento conforme PPR/CNEN e retirar o rótulo de rejeito radioativo apenas após atingir limite de dispensa e medição.',
    },
    {
      id: 'odontologia-broca',
      title: 'Broca odontológica descartada',
      category: 'Odontologia',
      sector: 'Odontologia',
      groups: ['E'],
      reference: 'RDC 222/2018, Anexo I - Grupo E e Art. 86',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Descartar brocas e limas usadas em saco plástico comum.',
      right: 'Brocas, limas e pontas diamantadas são perfurocortantes e devem ir para recipiente rígido identificado.',
    },
    {
      id: 'expurgo-abrigo',
      title: 'Armazenamento temporário no expurgo',
      category: 'Expurgo',
      sector: 'Expurgo',
      groups: ['A', 'D', 'E'],
      reference: 'RDC 222/2018, Arts. 31 a 35',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Guardar coletores de diferentes grupos sem identificação ou em área improvisada.',
      right: 'O armazenamento temporário deve ser identificado e organizado conforme grupos de RSS, frequência de coleta e estrutura prevista na RDC e PGRSS.',
    }
  ],
  en: [
    {
      id: 'samu',
      title: 'SAMU Care',
      category: 'Out-of-hospital Emergency',
      sector: 'SAMU',
      groups: ['E'],
      reference: 'RDC 222/2018, Arts. 86 to 89',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM6x_dPnnP5fi0MxCat9ErVsTA5RkAYFhUeDIRMKpCQuX7L6QiMaAHY8K2-XqTzIPo8UqFyOrN3KJF_ThJRRWvRLB2VMXPKxHv3TRuRnhu9bDcpRK6vmDdI5q70I7J5E46BsqYUAqNJMEtiSxK-ywVz7SODbGOsBO4cof8_wOwuSlLnXPfKbgJ6MgMvF5YQ3Zf38kbBRk0oJ52GXrzWkbMwN0mRwoB-NxMyVTWN2F5ehTNGdLycPIXg4Ok3bTUEeEwDIyiOmWHTBFj',
      wrong: 'Discarding venous access needles as common waste or in infectious plastic bags inside the ambulance.',
      right: 'Discard immediately in an identified rigid sharps container with lid, resistant to puncture, rupture, and leakage.',
    },
    {
      id: 'uti',
      title: 'Catheter Exchange in ICU',
      category: 'Intensive Care Unit',
      sector: 'ICU',
      groups: ['A', 'D'],
      reference: 'RDC 222/2018, Annex I - Groups A/D and Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Discarding clean plastic wrap in the white infectious bag.',
      right: 'Discard the catheter according to biological risk and the PGRSS, normally in the Group A flow when secretions or body fluids are present. Clean wrapping goes to Group D.',
      attention: 'Bins should have pedal-operated lids.',
    },
    {
      id: 'cc',
      title: 'Operating Room',
      category: 'Post-Operative',
      sector: 'Operating room',
      groups: ['A'],
      reference: 'RDC 222/2018, Annex I - Group A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1qvjiKgaA2i7XucKzr1OUphoL_HgQoPGfY5KyfNwOLpPg757zrcdnvr5U-WtpEtpjrGnnYdmcY1BfulQzU_Wd9CEDHqQhxzU-LwKzzYxxkM97d0ZUSIdri65yRpHj0Ws1fxM-5w2TORPDBes_iTwoLZ3kcusdpJV2wk-gAIObmJC1u941iWzOwYBRmcX4K0IcLKM3HCQUtqImPb1c-tgGWfvoYoTVnVuXAaFvnbYfQXNceHDD_AsVzxZRhkygDhbYaJ9xLC3yU0zy',
      wrong: 'Sending anatomical parts or tissues to common infectious waste.',
      right: 'Anatomical parts must follow the specific Group A/applicable subgroup flow, with identification, packaging, and destination defined in the PGRSS.',
    },
    {
      id: 'curativo-sangue',
      title: 'Bloody Dressing',
      category: 'Dressing room',
      sector: 'Dressings',
      groups: ['A'],
      reference: 'RDC 222/2018, Annex I - Group A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Discarding gauze or a bloody dressing as common waste because it looks small.',
      right: 'If blood or body fluid is present in free form, classify by biological risk and follow the Group A flow defined in the PGRSS.',
    },
    {
      id: 'luva-limpa',
      title: 'Glove Without Contamination',
      category: 'Procedure without secretion',
      sector: 'Outpatient care',
      groups: ['D'],
      reference: 'RDC 222/2018, Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Automatically classifying every glove used in care as infectious waste.',
      right: 'Gloves with no sign or suspicion of biological, chemical, or radiological contamination may be managed as Group D.',
    },
    {
      id: 'placa-petri',
      title: 'Petri Dish with Culture',
      category: 'Laboratory',
      sector: 'Laboratory',
      groups: ['A'],
      reference: 'RDC 222/2018, Annex I - Subgroup A1 and Art. 16',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Sending an inoculated plate directly to external collection in a white bag.',
      right: 'Cultures and culture media belong to subgroup A1 and must follow the defined treatment or internal flow before leaving the facility.',
    },
    {
      id: 'medicamento-vencido',
      title: 'Expired Medicine',
      category: 'Pharmacy',
      sector: 'Pharmacy',
      groups: ['B'],
      reference: 'RDC 222/2018, Annex I - Group B and Art. 59',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Discarding expired medicines in a common bin or sink.',
      right: 'Classify as Group B when chemical risk is present and follow treatment, logistics, or final destination defined in the PGRSS and licensing.',
    },
    {
      id: 'quimicos-incompativeis',
      title: 'Reagent Mixing',
      category: 'Chemical laboratory',
      sector: 'Laboratory',
      groups: ['B'],
      reference: 'RDC 222/2018, Art. 60 and Annexes III/IV',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Mixing different chemical leftovers in the same bottle to save space.',
      right: 'Incompatible chemical waste must be segregated, packaged, and identified separately according to risk and compatibility.',
    },
    {
      id: 'termometro-mercurio',
      title: 'Broken Mercury Thermometer',
      category: 'Sector accident',
      sector: 'Laboratory',
      groups: ['B', 'E'],
      reference: 'RDC 222/2018, Annex I - Group B and Art. 88',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Wrapping the glass in paper and discarding it as common waste.',
      right: 'Mercury creates chemical risk and broken glass creates sharps risk. The container must identify all risks present.',
    },
    {
      id: 'coletor-34',
      title: 'Full Sharps Container',
      category: 'Nursing station',
      sector: 'Nursing',
      groups: ['E'],
      reference: 'RDC 222/2018, Art. 87',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Compressing or shaking the container to fit more material.',
      right: 'Replace it according to demand, at 3/4 capacity, or as instructed by the manufacturer. Manual emptying and reuse are prohibited.',
    },
    {
      id: 'resto-isolamento',
      title: 'Food Leftover from Isolated Patient',
      category: 'Hospital cafeteria',
      sector: 'Cafeteria',
      groups: ['D', 'A'],
      reference: 'RDC 222/2018, Art. 84 and PGRSS risk assessment',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Sending automatically to composting without checking isolation or associated risk.',
      right: 'Composting is allowed only for food leftovers from patients who are not in isolation. In isolation, follow risk assessment and the PGRSS.',
    },
    {
      id: 'radioiodo',
      title: 'Patient Under Iodine-131 Therapy',
      category: 'Nuclear medicine',
      sector: 'Nuclear medicine',
      groups: ['C'],
      reference: 'RDC 222/2018, Arts. 33, 76 to 79',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Removing radioactive identification before measuring radiation level.',
      right: 'Store for decay according to PPR/CNEN and remove the radioactive waste label only after reaching the clearance level and measuring radiation.',
    },
    {
      id: 'odontologia-broca',
      title: 'Discarded Dental Bur',
      category: 'Dentistry',
      sector: 'Dentistry',
      groups: ['E'],
      reference: 'RDC 222/2018, Annex I - Group E and Art. 86',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Discarding used burs, files, or tips in a common plastic bag.',
      right: 'Burs, files, and diamond tips are sharps and must go into an identified rigid container.',
    },
    {
      id: 'expurgo-abrigo',
      title: 'Temporary Storage in Utility Room',
      category: 'Utility room',
      sector: 'Utility room',
      groups: ['A', 'D', 'E'],
      reference: 'RDC 222/2018, Arts. 31 to 35',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Storing containers from different groups without identification or in an improvised area.',
      right: 'Temporary storage must be identified and organized by RSS group, collection frequency, and the structure required by RDC and the PGRSS.',
    }
  ],
  es: [
    {
      id: 'samu',
      title: 'Atención SAMU',
      category: 'Emergencia extrahospitalaria',
      sector: 'SAMU',
      groups: ['E'],
      reference: 'RDC 222/2018, Arts. 86 a 89',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM6x_dPnnP5fi0MxCat9ErVsTA5RkAYFhUeDIRMKpCQuX7L6QiMaAHY8K2-XqTzIPo8UqFyOrN3KJF_ThJRRWvRLB2VMXPKxHv3TRuRnhu9bDcpRK6vmDdI5q70I7J5E46BsqYUAqNJMEtiSxK-ywVz7SODbGOsBO4cof8_wOwuSlLnXPfKbgJ6MgMvF5YQ3Zf38kbBRk0oJ52GXrzWkbMwN0mRwoB-NxMyVTWN2F5ehTNGdLycPIXg4Ok3bTUEeEwDIyiOmWHTBFj',
      wrong: 'Descartar agujas de acceso venoso en residuos comunes o en bolsas plásticas infectantes dentro de la ambulancia.',
      right: 'Descartar inmediatamente en recolector rígido, identificado, con tapa y resistente a punción, ruptura y fuga.',
    },
    {
      id: 'uti',
      title: 'Cambio de sonda en UCI',
      category: 'Unidad de cuidados intensivos',
      sector: 'UCI',
      groups: ['A', 'D'],
      reference: 'RDC 222/2018, Anexo I - Grupos A/D y Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Desechar el envoltorio plástico limpio en la bolsa blanca de infectantes.',
      right: 'Descartar la sonda según el riesgo biológico y el PGRSS, normalmente en el flujo del Grupo A cuando haya secreciones o líquidos corporales. El envoltorio limpio va al Grupo D.',
      attention: 'Las papeleras deben tener tapa con accionamiento por pedal.',
    },
    {
      id: 'cc',
      title: 'Centro quirúrgico',
      category: 'Posoperatorio',
      sector: 'Centro quirúrgico',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Grupo A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1qvjiKgaA2i7XucKzr1OUphoL_HgQoPGfY5KyfNwOLpPg757zrcdnvr5U-WtpEtpjrGnnYdmcY1BfulQzU_Wd9CEDHqQhxzU-LwKzzYxxkM97d0ZUSIdri65yRpHj0Ws1fxM-5w2TORPDBes_iTwoLZ3kcusdpJV2wk-gAIObmJC1u941iWzOwYBRmcX4K0IcLKM3HCQUtqImPb1c-tgGWfvoYoTVnVuXAaFvnbYfQXNceHDD_AsVzxZRhkygDhbYaJ9xLC3yU0zy',
      wrong: 'Enviar piezas anatómicas o tejidos al residuo infectante común.',
      right: 'Las piezas anatómicas deben seguir el flujo específico del Grupo A/subgrupo aplicable, con identificación, acondicionamiento y destinación definidos en el PGRSS.',
    },
    {
      id: 'curativo-sangue',
      title: 'Curativo con sangre',
      category: 'Sala de curativos',
      sector: 'Curativos',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Grupo A',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Descartar gasa o curativo con sangre como residuo común por parecer un material pequeño.',
      right: 'Si hay sangre o líquido corporal libre, clasificar por riesgo biológico y seguir el flujo del Grupo A definido en el PGRSS.',
    },
    {
      id: 'luva-limpa',
      title: 'Guante sin contaminación',
      category: 'Procedimiento sin secreción',
      sector: 'Ambulatorio',
      groups: ['D'],
      reference: 'RDC 222/2018, Art. 82',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Clasificar automáticamente todo guante usado en la asistencia como residuo infectante.',
      right: 'Los guantes sin señales o sospecha de contaminación biológica, química o radiológica pueden manejarse como Grupo D.',
    },
    {
      id: 'placa-petri',
      title: 'Placa de Petri con cultivo',
      category: 'Laboratorio',
      sector: 'Laboratorio',
      groups: ['A'],
      reference: 'RDC 222/2018, Anexo I - Subgrupo A1 y Art. 16',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Enviar una placa inoculada directamente a la recolección externa en bolsa blanca.',
      right: 'Los cultivos y medios de cultivo pertenecen al subgrupo A1 y deben seguir el tratamiento o flujo definido antes de salir de la unidad, conforme al PGRSS.',
    },
    {
      id: 'medicamento-vencido',
      title: 'Medicamento vencido',
      category: 'Farmacia',
      sector: 'Farmacia',
      groups: ['B'],
      reference: 'RDC 222/2018, Anexo I - Grupo B y Art. 59',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Descartar medicamentos vencidos en una papelera común o en el desagüe.',
      right: 'Clasificar como Grupo B cuando exista riesgo químico y seguir el tratamiento, logística o destinación previstos en el PGRSS y en el licenciamiento.',
    },
    {
      id: 'quimicos-incompativeis',
      title: 'Mezcla de reactivos',
      category: 'Laboratorio químico',
      sector: 'Laboratorio',
      groups: ['B'],
      reference: 'RDC 222/2018, Art. 60 y Anexos III/IV',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaG4kwlCOPwPgbuuiB7gzHDaWsleQUb395dnT2x4ZxD7LlfGUngC5sP-XVIHj5vF90MKzRqNJSLwKORWWRNdb_RTMFnaVK_uSH4xOmEXzP1V9gXtypUbRPPLHp3T9GT0S67I9_w-GbmP6cOJpuX0eK3cU3UNooA6KtUfNPKnR4-_lr2kFbewrafBiATbgnX2jorWOtbMsH7j8minJO_SgoN4VdAQRgj84xU73LAQdDPl2RrX193TDm3pLD3djmsNPzyDWPsHq2fTHl',
      wrong: 'Mezclar sobrantes químicos diferentes en el mismo frasco para ahorrar espacio.',
      right: 'Los residuos químicos incompatibles deben segregarse, acondicionarse e identificarse por separado según el riesgo y la compatibilidad.',
    },
    {
      id: 'termometro-mercurio',
      title: 'Termómetro con mercurio roto',
      category: 'Accidente en el sector',
      sector: 'Laboratorio',
      groups: ['B', 'E'],
      reference: 'RDC 222/2018, Anexo I - Grupo B y Art. 88',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Juntar el vidrio con papel y descartarlo como residuo común.',
      right: 'Existe riesgo químico por el mercurio y riesgo punzocortante por el vidrio. El recipiente debe identificar todos los riesgos presentes.',
    },
    {
      id: 'coletor-34',
      title: 'Recolector de punzocortantes lleno',
      category: 'Puesto de enfermería',
      sector: 'Enfermería',
      groups: ['E'],
      reference: 'RDC 222/2018, Art. 87',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Compactar o sacudir el recolector para que quepa más material.',
      right: 'Sustituirlo según la demanda, al alcanzar 3/4 de la capacidad o según el fabricante. Está prohibido vaciarlo manualmente y reutilizarlo.',
    },
    {
      id: 'resto-isolamento',
      title: 'Resto alimentario de paciente en aislamiento',
      category: 'Comedor hospitalario',
      sector: 'Comedor',
      groups: ['D', 'A'],
      reference: 'RDC 222/2018, Art. 84 y evaluación de riesgo del PGRSS',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0RUtsfI5RpolMN02EJrGn1M8DKfcrv8QUAx6bxNhcP6SE0UMP0Csmjyvux8iYK46JEZTyoSkOz8-KeVlpb-plYphN7009gDu3XDtTxLw6z2F0q60cazziSVR11GT6sisDNd2csQKnzjiTMyi4_lWHCXGAI-wsfJXiISChPJv3ta9kgz6sXJ_A1I_d1Zg7GETA_dbf2gAi_ectIdy0drd4tCGz0kE_-qebuj7u9RAP2K3KNPRhSHppzBymiOb0Km53uOAB3fVrrQHq',
      wrong: 'Enviar automáticamente a compostaje sin verificar aislamiento o riesgo asociado.',
      right: 'El compostaje solo se permite para restos alimentarios de pacientes que no estén en aislamiento. En aislamiento, debe seguirse la evaluación de riesgo y el PGRSS.',
    },
    {
      id: 'radioiodo',
      title: 'Paciente en terapia con yodo-131',
      category: 'Medicina nuclear',
      sector: 'Medicina nuclear',
      groups: ['C'],
      reference: 'RDC 222/2018, Arts. 33, 76 a 79',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkTKvBqo4d10NWR1gef27d99lgx5StWrhHqEjPq1YikehYcsfCa5GWAQuJc62D-xxkSfBLSjNayDh5GSNaOfpxamm4cYhm88Whxhaca3gnH-x1XTvmrrhDlsx6oi6EqnQu1vk4_diFvfI-HxxtwbN6RkmTJjsUcl18wgxXc_KAQ3DU24af58Bf8-9tcHzgrUqQ4Qq3TMh36lWhbDZZMGOwWdOtEKxjsVB-z8QcmmpCOXpurVJuyVgspDS8YCHhLRdOSey7_wERoED2',
      wrong: 'Retirar la identificación radioactiva antes de medir el nivel de radiación.',
      right: 'Almacenar para decaimiento conforme al PPR/CNEN y retirar la etiqueta de rechazo radioactivo solo después de alcanzar el límite de dispensa y realizar la medición.',
    },
    {
      id: 'odontologia-broca',
      title: 'Fresa odontológica descartada',
      category: 'Odontología',
      sector: 'Odontología',
      groups: ['E'],
      reference: 'RDC 222/2018, Anexo I - Grupo E y Art. 86',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0ztjmOIWXKc6pb6Ge2CdimcvWatS6dn4vPh0TZGMa-XXMN50OwjbIta-I-OZR-JrrUBEIu_-J7RnLksNt1kysOyKJ518llBeZekh2YgMChXLTqN77UXR8J9SyEJhD2mp3rhsNW4OclEN-KFwPHp_6IV161FM4L9csA59xxOWljGZVh_9O4hQNnMCaOPSBlrgc23OP_hOTlkTy0PYmHw-Vmn5rDVUIV6AHb_m3JZvmwuLliVA37khMzho2M_PFetOsGzh9Pd2pd0WB',
      wrong: 'Descartar fresas, limas o puntas utilizadas en una bolsa plástica común.',
      right: 'Fresas, limas y puntas diamantadas son punzocortantes y deben descartarse en recipiente rígido identificado.',
    },
    {
      id: 'expurgo-abrigo',
      title: 'Almacenamiento temporal en el expurgo',
      category: 'Expurgo',
      sector: 'Expurgo',
      groups: ['A', 'D', 'E'],
      reference: 'RDC 222/2018, Arts. 31 a 35',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBbFfBb0NST1QkQ5NhsgqdWhqt8kHvJt3VPWMKgPqUT7yu6opBTRi4hIggUs8Muhg7e0a3WTW5G7B_9ncGahXJort60qU4dHsAYdywSsF0h6cNaeD6Ait-rm6RO2b3A5LwuBzQqOutA1Wo2SvuZN0xmHvhsu566lKf_m0Mr3QZquRpRtjasxhGRB-BngHe-Smh6f0c31AR0JhpCtXfWZ_F_DISoeQwvWlbtIYRqIHsWCzPS0fTqYBZ9FTisYS2ap4IpSomGKYSdMZ_',
      wrong: 'Guardar recolectores de diferentes grupos sin identificación o en un área improvisada.',
      right: 'El almacenamiento temporal debe estar identificado y organizado según los grupos de RSS, la frecuencia de recolección y la estructura prevista en la RDC y el PGRSS.',
    }
  ]
};

export const QUIZ: Record<Language, QuizQuestion[]> = {
  pt: [
    {
      id: 1,
      category: 'Resíduos Infectantes',
      question: 'Paciente apresenta curativo com sangue vivo após procedimento. Qual o descarte correto segundo o protocolo Grupo A?',
      options: [
        'Saco branco leitoso com símbolo de risco biológico.',
        'Recipiente rígido resistente a perfurações (Perfurocortantes).',
        'Lixeira comum (saco preto/cinza) para posterior triagem.'
      ],
      correctAnswer: 0,
      explanation: 'Materiais com sangue excessivo devem ser segregados imediatamente no saco branco leitoso para prevenir riscos biológicos.'
    },
    {
      id: 2,
      category: 'Segurança com Perfurocortantes',
      question: 'Qual a conduta correta ao finalizar o uso de uma agulha de punção?',
      options: [
        'Reencapar e descartar no saco branco.',
        'Descartar imediatamente sem reencapar na caixa amarela.',
        'Colocar na bandeja para descarte posterior pela equipe de limpeza.'
      ],
      correctAnswer: 1,
      explanation: 'Nunca reencape agulhas. O descarte deve ser imediato no coletor rígido (Grupo E).'
    }
  ],
  en: [
    {
      id: 1,
      category: 'Infectious Waste',
      question: 'Patient presents a dressing with brisk bleeding after a procedure. What is the correct disposal according to Group A protocol?',
      options: [
        'Milky white bag with biohazard symbol.',
        'Rigid puncture-resistant container (Sharps).',
        'Common trash can (black/gray bag) for later sorting.'
      ],
      correctAnswer: 0,
      explanation: 'Materials with excessive blood must be immediately segregated in the milky white bag to prevent biological risks.'
    },
    {
      id: 2,
      category: 'Sharps Safety',
      question: 'What is the correct procedure when finishing the use of a puncture needle?',
      options: [
        'Recap and discard in the white bag.',
        'Discard immediately without recapping in the yellow box.',
        'Place on the tray for later disposal by the cleaning staff.'
      ],
      correctAnswer: 1,
      explanation: 'Never recap needles. Disposal must be immediate in the rigid collector (Group E).'
    }
  ],
  es: [
    {
      id: 1,
      category: 'Residuos infectantes',
      question: 'Un paciente presenta un curativo con sangre después de un procedimiento. ¿Cuál es el descarte correcto según el manejo del Grupo A?',
      options: [
        'Bolsa blanca lechosa con símbolo de riesgo biológico.',
        'Recipiente rígido resistente a punción (punzocortantes).',
        'Residuo común para clasificación posterior.'
      ],
      correctAnswer: 0,
      explanation: 'Los materiales con sangre o líquidos corporales libres deben segregarse conforme al riesgo biológico y al PGRSS, evitando su mezcla con residuos comunes.'
    },
    {
      id: 2,
      category: 'Seguridad con punzocortantes',
      question: '¿Cuál es la conducta correcta después de utilizar una aguja de punción?',
      options: [
        'Reencapuchar y descartar en la bolsa blanca.',
        'Descartar inmediatamente, sin reencapuchar, en el recolector rígido para punzocortantes.',
        'Colocar en una bandeja para descarte posterior por el equipo de limpieza.'
      ],
      correctAnswer: 1,
      explanation: 'Las agujas no deben reencapucharse. El descarte debe ser inmediato en recipiente rígido, identificado y resistente a punción, ruptura y fuga.'
    }
  ]
};
